# bsc 生态系统交易对配置

bsc_ecosystem:
  - CHEEMS-USDT
  - BABYDOGE-USDT
  - ALE-USDT
  - TSTBSC-USDT
  - BANANAS3I-USDT
  - CAT-USDT
  - BMT-USDT
  - MUBARAK-USDT
  - BROCCOLI-USDT
  - TUT-USDT
  - FHE-USDT
  - GM-USDT
  - KOMA-USDT
  - AICELL-USDT
  - FOUR-USDT
