# sol 生态系统交易对配置

sol_ecosystem:
  - SOL-USDT
  - LINK-USDT
  - BONK-USDT
  - JUP-USDT
  - MSOL-USDT
  - RAY-USDT
  - HNT-USDT
  - WIF-USDT
  - JTO-USDT
  - PYTH-USDT
  - W-USDT
  - LAYER-USDT
  - GIGA-USDT
  - DRIFT-USDT
  - PNUT-USDT
  - ORCA-USDT
  - GMT-USDT
  - ALCH-USDT
  - SUSHI-USDT
  - ZBCN-USDT
  - HONEY-USDT
  - BOME-USDT
  - SONIC-USDT
  - KMNO-USDT
  - AUDIO-USDT
  - FIDA-USDT
  - TAI-USDT
  - ACS-USDT
  - TNSR-USDT
  - FWOG-USDT
  - MNDE-USDT
  - BMT-USDT
  - JELLYJELLY-USDT
  - WEN-USDT
  - SWARMS-USDT
  - J-USDT
  - ATLAS-USDT
  - STEP-USDT
  - CRWN-USDT
  - POLIS-USDT
  - BOTIFY-USDT
  - SAMO-USDT
  - BONGO-USDT
  - LIKE-USDT
  - SRM-USDT
  - ROA-USDT
  - SLIM-USDT
  - GST-USDT
  - BENDOG-USDT
  - LOULOU-USDT
  - SBR-USDT
  - STREAM-USDT
  - MBS-USDT
  - GARI-USDT
  - HADES-USDT
  - SOLS-USDT
  - IQ50-USDT
  - WLKN-USDT
  - SPICE-USDT
  - SFT-USDT
  - PUMPAI-USDT
  - AQA-USDT
  - SUNNY-USDT
  - DOGIN-USDT
  - DOAI-USDT
  - MTOS-USDT
  - DOGGO-USDT
  - TOK-USDT
