services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=timescaledb
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - quants_shared_net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: quants_lab
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_ql:/data/db
    restart: unless-stopped
    networks:
      - quants_shared_net

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: changeme
    ports:
      - "28081:8081"
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - quants_shared_net

networks:
  quants_shared_net:
    driver: bridge
    name: quants_lab_shared_network

volumes:
  mongodb_data_ql:
  timescale_data:
