tasks:
  gateio_sol_ecosystem_downloader:
    enabled: true
    task_class: tasks.data_collection.simple_candles_downloader.SimpleCandlesDownloader
    frequency_hours: 999999
    config:
      connector_name: gate_io
      trading_pairs:
      - SOL-USDT
      - LINK-USDT
      - BONK-USDT
      - JUP-USDT
      - MSOL-USDT
      - RAY-USDT
      - HNT-USDT
      - WIF-USDT
      - JTO-USDT
      - PYTH-USDT
      - W-USDT
      - LAYER-USDT
      - GIGA-USDT
      - DRIFT-USDT
      - PNUT-USDT
      - ORCA-USDT
      - GMT-USDT
      - ALCH-USDT
      - SUSHI-USDT
      - ZBCN-USDT
      - HONEY-USDT
      - BOME-USDT
      - SONIC-USDT
      - KMNO-USDT
      - AUDIO-USDT
      - FIDA-USDT
      - TAI-USDT
      - ACS-USDT
      - TNSR-USDT
      - FWOG-USDT
      - MNDE-USDT
      - BMT-USDT
      - JELLYJELLY-USDT
      - WEN-USDT
      - SWARMS-USDT
      - J-USDT
      - ATLAS-USDT
      - STEP-USDT
      - CRWN-USDT
      - POLIS-USDT
      - BOTIFY-USDT
      - SAMO-USDT
      - CLOUD-USDT
      - BONGO-USDT
      - LIKE-USDT
      - SRM-USDT
      - ROA-USDT
      - SLIM-USDT
      - GST-USDT
      - BILLY-USDT
      - BENDOG-USDT
      - LOULOU-USDT
      - SBR-USDT
      - STREAM-USDT
      - MBS-USDT
      - GARI-USDT
      - DUST-USDT
      - HADES-USDT
      - SOLS-USDT
      - IQ50-USDT
      - WLKN-USDT
      - SPICE-USDT
      - SFT-USDT
      - PUMPAI-USDT
      - AQA-USDT
      - SUNNY-USDT
      - DOGIN-USDT
      - DOAI-USDT
      - MTOS-USDT
      - DOGGO-USDT
      - TOK-USDT
      intervals:
      - 15m
      - 4h
      - 1d
      - 1h
      days_data_retention: 30
      timescale_config:
        db_host: timescaledb
        db_port: 5432
        db_user: admin
        db_password: admin
        db_name: timescaledb
